env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  binary: cloud-platform
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=cloud-platform
changelog:
  sort: asc
  filters:
    exclude:
    - Merge pull request
    - Merge branch
    - go mod tidy
brews:
  - tap:
      owner: ministryofjustice
      name: homebrew-cloud-platform-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: https://user-guide.cloud-platform.service.justice.gov.uk/#cloud-platform-user-guide
    description: Multi-purpose CLI for Ministry of Justice Cloud Platform.
    license: MIT
    install: |
      bin.install "cloud-platform"
    dependencies:
    - name: go
